spring:
  application:
    name: analyzer

  datasource:
    hikari:
      connection-timeout: 5000 # 5초만 기다리고 바로 에러 내뱉게 설정
    url: jdbc:mysql://localhost:3306/kotona?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # ddl-auto와 show-sql은 jpa 바로 밑
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          # 특정 버전을 명시하기보다 최신 버전용 공통 Dialect 권장
          dialect: org.hibernate.dialect.MySQLDialect
          # MySQL 8.0 이상이면 명시하지 않아도 JPA가 자동으로 잘 잡음

# 커스텀 변수 (제미나이 설정)
gemini:
  project-id: ${GCP_PROJECT_ID}
  api-key: ${GEMINI_API_KEY}

# 유령 서버 피해 이동
server:
  port: 8081